name: bluesy
description: A Flutter widget library for serial Bluetooth communication between smart phones and microcontrollers.
version: 0.0.3
repository: https://github.com/ernpao/bluesy

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^4.3.2+2
  flutter_bluetooth_serial: ^0.2.2